language: c
compiler:
  - gcc
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev"
script:
  - "work/packaging/build_debian.sh"
after_failure:
  - "for log in /tmp/liberty-eiffel-logs/*.log; do echo '**** LOG:' $log; cat $log; done"
cache:
  - apt
