language: c
compiler:
  - gcc
env:
  - LANG=C
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev libgc1c2 coreutils"
install:
  - "./install.sh -plain -bootstrap"
  - "work/packaging/build_debian.sh"
  - "sudo dpkg -c work/packaging/debs/liberty-eiffel-tools_*.deb"
  - "sudo dpkg -i work/packaging/debs/*.deb"
# - "for log in target/log/liberty-eiffel-*.log; do echo; echo '~~~~~~~~~~~~~~~~ LOG:' $log; cat $log; done"
# - "for se in /etc/xdg/liberty-eiffel/*.se; do echo; echo '~~~~~~~~~~~~~~~~ SE:' $se; cat $se; done"
  - "rm -rf $HOME/.config/liberty-eiffel"
script:
  - "work/se_run_tutorial.sh"
cache:
  - apt
