language: c
compiler:
  - gcc
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev libgc1c2"
script:
  - "work/packaging/build_debian.sh"
  - "rm -rf /tmp/liberty-eiffel-logs"
  - "sudo dpkg -i work/packaging/debs/*.deb"
  - "which se"
  - "find $(pwd)/tutorial -name 'aux*' -prune -o -name '*.e' '(' -execdir $(pwd)/work/se_run.sh {} ';' -o -quit ')'"
after_failure:
  - "test -d /tmp/liberty-eiffel-logs && for log in /tmp/liberty-eiffel-logs/*.log; do echo '**** LOG:' $log; cat $log; done"
cache:
  - apt
