language: c
compiler:
  - gcc
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev"
script:
  - "work/packaging/build_debian.sh"
  - "rm -rf /tmp/liberty-eiffel-logs"
  - "sudo dpkg -i work/packaging/debs/*.deb"
  - "find tutorial -name aux\\* -prune -o -name \\*.e -print | while read e; do echo $e; ( exe=$(basename $e .e).exe; cd $(dirname $e); se c -clean -style_warning -o $exe $e && $exe && rm -f $exe ) || exit 1; done"
after_failure:
  - "test -d /tmp/liberty-eiffel-logs && for log in /tmp/liberty-eiffel-logs/*.log; do echo '**** LOG:' $log; cat $log; done"
cache:
  - apt
