language: c
compiler:
- gcc
env:
  global:
  - LANG=C
  - PKG_DATE=$(date -u +'%Y%m%d.%H%M%S')
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq g++ gccxml reprepro devscripts docbook-to-man libgc-dev libperl-dev libgc1c2 coreutils netcat-openbsd curl reprepro
install:
- work/packaging/build_debian.sh -commit."$PKG_DATE"
- sudo dpkg -i work/packaging/debs/*.deb
script:
- work/packaging/build_debian.sh -deploy
- work/se_run_tutorial.sh
notifications:
  slack:
    secure: NLCxaRIda57mSi5Bv8tYJp+sB110tXtmOPRbcdqdAdWjv5csatyqUB3U/QCsNPR0KrUE4Z8Abp+LS75TZXthKUs6It8Emns4RZtdjsJBZBOc1jD89YNRt2ogDZTXJh47XymvruMuBXRKOrAthBRFFI4Zsk45ivgfw0egcN7+Ua8=
